server {
    listen 80;

    location /auth/ {
        proxy_pass http://service_a:5001;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /orders {
        proxy_pass http://service_b:5002;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /health {
        return 200 '{"status": "gateway healthy"}';
        add_header Content-Type application/json;
    }
}