server {
    listen 80;
    server_name localhost;
    server_tokens off;

    location = /secure { return 301 https://localhost:8443/secure; }

    location /auth/  { proxy_pass http://service_a:5001; proxy_set_header Authorization $http_authorization; }
    location /orders { proxy_pass http://service_b:5002; proxy_set_header Authorization $http_authorization; }
    location /health { proxy_pass http://service_b:5002; }
    location /config { proxy_pass http://service_b:5002; }
    location /ping   { proxy_pass http://service_b:5002; }
}

server {
    listen 443 ssl;
    server_name localhost;
    server_tokens off;
    more_clear_headers Server;                 # header_leak: nonem Server galveni

    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always; 

    location = /secure { return 200 "secure endpoint\n"; }   # ssl_verify_disabled -> 200

    location /auth/  { proxy_pass http://service_a:5001; proxy_set_header Authorization $http_authorization; }
    location /orders { proxy_pass http://service_b:5002; proxy_set_header Authorization $http_authorization; }
    location /health { proxy_pass http://service_b:5002; }
    location /config { proxy_pass http://service_b:5002; }
    location /ping   { proxy_pass http://service_b:5002; }
}
