server {
    listen 80;
    server_name localhost;
    server_tokens on;       # header_leak: atklaj servera info
    add_header X-Powered-By "nginx" always;

    location = /secure { return 200 "insecure endpoint\n"; }    # nav redirect, nav HSTS

    location /auth/  { proxy_pass http://service_a:5001; proxy_set_header Authorization $http_authorization; }
    location /orders { proxy_pass http://service_b:5002; proxy_set_header Authorization $http_authorization; }
    location /health { proxy_pass http://service_b:5002; }
    location /config { proxy_pass http://service_b:5002; }
    location /ping   { proxy_pass http://service_b:5002; }
}